spring:
  datasource:
    url: jdbc:mysql://localhost::3306/sfg-dev
    username: sfg-dev-user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MYSQL5InnoDBDialect
    database: mysql
    show-sql: true